### ISSUE TITLE
Incorrect movement Japanese ->Shift-Jis

### ISSUE THREAD

**Issue by nil-ew** [vinsworldcom/nppColHighlight#13] opened 2023-01-22 10:50 UTC
Goog Day, VinsWorldcom.
Thank you for your addition.
When encoding text:  Character set-> Japanese ->Shift-Jis
The cursor is in front Highlight Current Column
![7](https://user-images.githubusercontent.com/123297763/213911931-654df2b1-487d-462a-969a-810da0999fb8.png)

**Comment by vinsworldcom** [comment] 2023-01-23 11:35
Known issue - this only works with fixed-width fonts.  Happy to accept a pull request to fix it.

Duplicate of #7 - closing.

**Closed as completed** 2023-01-23 11:40 UTC
